In [3]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [29]:
df = pd.read_csv("test.csv", skiprows=6)

In [30]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 440 entries, 0 to 439
Data columns (total 78 columns):
[run number]                        440 non-null int64
max_altitude_food_available         440 non-null int64
mean_ash_intensity                  440 non-null int64
ash_eruption_distance_2             440 non-null int64
increase_temp_variation             440 non-null int64
ash_eruption_radius                 440 non-null int64
growback_rate                       440 non-null int64
random_ash_fall                     440 non-null float64
decrease_connection                 440 non-null int64
max_deviation_prec                  440 non-null int64
cultural_capital_distribution       440 non-null object
show-graticules?                    440 non-null bool
ash_fallout                         440 non-null object
max_temp_change                     440 non-null int64
show_volcano_impact                 440 non-null bool
max_deviation_temp                  440 non-null int64
volcano_duration_effect             440 non-null int64
threshold_location_knowledge        440 non-null int64
average_group_size                  440 non-null int64
show_links                          440 non-null bool
volcano_eruption_distance           440 non-null int64
mobility_size_factor                440 non-null int64
max_food_patch                      440 non-null int64
max_shared_locations                440 non-null int64
ash_eruption_angle_2                440 non-null int64
debug?                              440 non-null bool
ash_wind_direction_2                440 non-null int64
optimal_temperature                 440 non-null int64
cooperation_radius                  440 non-null int64
stdev_group_size                    440 non-null int64
cone_impact_2                       440 non-null int64
ash_eruption_distance_1             440 non-null int64
optimal_precipitation               440 non-null int64
max_resource_patch                  440 non-null int64
percentage_ash                      440 non-null int64
decay_exponent                      440 non-null float64
split_min_size                      440 non-null int64
stdv_ash_intensity                  440 non-null int64
increase_prec_variation             440 non-null int64
number_of_bands                     440 non-null int64
variation_delay                     440 non-null int64
max_effectiveness                   440 non-null int64
maximum_days_moving                 440 non-null int64
decay_type                          440 non-null object
merge_max_size                      440 non-null int64
cultural_capital_mutation           440 non-null int64
ash_eruption_distribution           440 non-null object
mean_cultural_capital               440 non-null int64
color_clusters?                     440 non-null bool
start_event                         440 non-null int64
environment_delay                   440 non-null int64
ash_eruption_angle_1                440 non-null int64
resources_tool                      440 non-null int64
ash_wind_direction_1                440 non-null int64
stdv_cultural_capital               440 non-null int64
max_prec_change                     440 non-null int64
standard_birth_rate                 440 non-null float64
cone_impact_1                       440 non-null int64
[step]                              440 non-null int64
average_temperature_of_patches      440 non-null float64
average_precipitation_of_patches    440 non-null float64
impact_by_ash                       440 non-null int64
death_by_volcano                    440 non-null int64
death_by_ash                        440 non-null int64
event_cultural_capital_loss         440 non-null int64
lost_resources                      440 non-null int64
average_food_available              440 non-null float64
average_resources_available         440 non-null float64
number_of_communities               440 non-null int64
average_community_size              440 non-null float64
number_of_links                     440 non-null int64
average_knowledge_locations         440 non-null float64
average_cultural_capital            440 non-null float64
average_technology_level            440 non-null float64
average_time_spent_moving           440 non-null float64
mean_group_size                     440 non-null float64
total_number_of_bands               440 non-null int64
total_population                    440 non-null int64
dtypes: bool(5), float64(13), int64(56), object(4)
memory usage: 253.2+ KB

In [31]:
df.sort_values(by = "[run number]")

,[run number],max_altitude_food_available,mean_ash_intensity,ash_eruption_distance_2,increase_temp_variation,ash_eruption_radius,growback_rate,random_ash_fall,decrease_connection,max_deviation_prec,...,number_of_communities,average_community_size,number_of_links,average_knowledge_locations,average_cultural_capital,average_technology_level,average_time_spent_moving,mean_group_size,total_number_of_bands,total_population
0,1,2500,50,50,0,40,8,0.3,1,3,...,0,1.000000,0,0.000000,0.000000,0.000000,0.000000,0.000000,0,0
23,1,2500,50,50,0,40,8,0.3,1,3,...,174,3.293103,510,0.250000,38.970334,36.594072,0.000000,23.186856,776,17993
49,1,2500,50,50,0,40,8,0.3,1,3,...,150,3.086667,410,2.490754,42.652982,38.250000,0.669940,26.084320,676,17633
65,1,2500,50,50,0,40,8,0.3,1,3,...,141,3.070922,378,4.553030,43.765923,38.346970,0.889249,26.925758,660,17771
153,1,2500,50,50,0,40,8,0.3,1,3,...,118,3.016949,305,5.351327,47.354836,39.217699,0.971011,17.925664,565,10128
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
377,40,2500,50,50,0,40,8,0.3,1,3,...,146,3.095890,376,0.684192,40.150080,36.884120,0.190264,24.818312,699,17348
383,40,2500,50,50,0,40,8,0.3,1,3,...,135,3.044444,331,2.292237,41.449213,37.213090,0.649916,26.238965,657,17239
398,40,2500,50,50,0,40,8,0.3,1,3,...,130,3.000000,317,4.819095,44.194631,38.435511,0.977179,27.549414,597,16447
430,40,2500,50,50,0,40,8,0.3,1,3,...,120,2.725000,242,5.311918,48.024098,39.687151,0.983216,20.150838,537,10821
369,40,2500,50,50,0,40,8,0.3,1,3,...,158,3.253165,440,0.250000,38.151095,35.864295,0.930794,23.395257,759,17757

In [28]:
df.columns

Index(['0', '520', '0.1', '180'], dtype='object')